name: experiment_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.9.13
- scikit-learn
- pandas
- pip
- pip:
  - azureml-defaults
  - azureml-mlflow
  - nltk
  - numpy
  - bs4
  - matplotlib
  - azureml-pipeline-core
  - azureml-pipeline-steps
  - azureml-widgets
  - tld
  - xgboost
  - lightgbm